[package]
name = "listen-notify"
version = "0.1.0"
edition = "2021"

[dependencies]
fsevent-sys = "4.1.0"
bitflags = "1.0.4"
crossbeam-channel = "0.5.0"
filetime = "0.2.6"
libc = "0.2.4"
serde = { version = "1.0.89", features = ["derive"], optional = true }
walkdir = "2.0.1"